name: Test and build TenXCards

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Run API unit tests
      run: dotnet test TenXCards.API.Tests --no-restore --verbosity normal --collect:"XPlat Code Coverage"

  build-api-and-frontend:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build API
      run: dotnet build TenXCards.API --no-restore

    - name: Build Frontend
      run: dotnet build TenXCards.Frontend --no-restore
      

      
